# Generated by Django 6.0.5 on 2026-05-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_order_alter_bills_order_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservations',
        ),
    ]
